controlspring.application.name=MobileDb

# Kisenyi DB
# Kisenyi DB
spring.datasource.kisenyi.jdbc-url=jdbc:mysql://localhost:3306/Kisenyi
spring.datasource.kisenyi.username=root
spring.datasource.kisenyi.password=OmaqTower@6622
spring.datasource.kisenyi.driver-class-name=com.mysql.cj.jdbc.Driver

# Customer DB
spring.datasource.customer.jdbc-url=jdbc:mysql://localhost:3306/Customer
spring.datasource.customer.username=root
spring.datasource.customer.password=OmaqTower@6622
spring.datasource.customer.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect




# Server port
server.port=8080

jenga.merchantCode=1099811292
jenga.apiKey=XKz6W5CesqkJ53vjc1iCg/1CWcxs+6rC4VZvx1lydOkaq1g+lJ55OTknpFNLXTKJ6hSzesJ2tqo7Qfh5PkzoIQ==
jenga.consumerSecret=13EnMbN0e32V0uviHJd1m5GVs3FL1y
jenga.baseUrl=https://uat.finserve.africa
jenga.privateKeyPath=classpath:keys/jenga_private.pem
jenga.publicKeyPath=classpath:keys/jenga_public.pem

# Use the same credentials you registered in the Jenga IPN portal
spring.security.user.name=TNTHAWER1@GMAIL.COM
spring.security.user.password=Omaq!Tower@2211!

# daraja.securityCredential=iIpud58EdPZBKK0WHwZ0lG/SnpMarokdSzyDcJx32BV/3DG9X+wArGH/61CgI6ZBDlWxoXuOp6pWl/ehYN/R5WdLNITb08LuypluHYn6F/x3s8/vI0hOD3qk8dLUK4It4Hb86B5LKhp+lykcKIVLv5M3Low6H58LtxwNUxSKGkVssoD4DsuK6mzCUcfC8r1SZKa6LS64k4AONPVmuns5pwdkLnWHDUz1OVm1iKCG7t4HckHVls6l8dOkGqiXE4RULF4kLyAbUy2eJ9zjYjaeGKO7QduS/OAGM7MurGhYp7bJOUXClyn1+vshyreAoPHOH5eJquOXhlACJoSuV1GLYQ==



# Daraja

# OAuth credentials
daraja.consumerKey=W9kHXM2PyhTeGriRo7At4ESKC2CAoLIceh9BU2W9uq8cNEtZ
daraja.consumerSecret=GYvBjGd58XGVdMYBq6SbaTidQjgdWZNM0pWqQ3PecY2fV0juWXRVpsRsGtP7GFJS
daraja.tokenUrl=https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials

# STK Push
daraja.stkPushUrl=https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
daraja.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
daraja.stkResultUrl=https://geomagnetic-confessedly-juanita.ngrok-free.dev/callback/stkpush/result
daraja.stkTimeoutUrl=https://geomagnetic-confessedly-juanita.ngrok-free.dev/callback/stkpush/timeout
daraja.shortcode=174379

# B2C
daraja.b2cUrl=https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest
daraja.b2cResultUrl=https://geomagnetic-confessedly-juanita.ngrok-free.dev/callback/result
daraja.b2cTimeoutUrl=https://geomagnetic-confessedly-juanita.ngrok-free.dev/callback/timeout
daraja.b2cShortcode=600998

# B2C test credentials
daraja.initiatorName=testapi
daraja.initiatorPassword=Safaricom123!!
daraja.certificatePath=certs/SandboxCertificate.cer

# Shortcode and test parties

daraja.partyA=600000
daraja.partyB=254708374149






