package com.example.MobileDb.service.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

public class PaymentRequest {

    @JsonProperty("OriginatorConversationID")
    private String originatorConversationID;

    @JsonProperty("InitiatorName")
    @NotBlank
    private String initiatorName;

    @JsonProperty("SecurityCredential")
    private String securityCredential; // generated by service, not required on controller side

    @JsonProperty("CommandID")
    @NotBlank
    private String commandID;

    @JsonProperty("Amount")
    @NotNull
    @Min(1)
    private Double amount;

    @JsonProperty("PartyA")
    @NotBlank
    private String partyA;

    @JsonProperty("PartyB")
    @NotBlank
    private String partyB;

    @JsonProperty("Remarks")
    private String remarks;

    @JsonProperty("QueueTimeOutURL")
    @NotBlank
    private String queueTimeOutURL;

    @JsonProperty("ResultURL")
    @NotBlank
    private String resultURL;

    @JsonProperty("Occasion")
    private String occasion;

    // --- New provenance field ---
    @JsonProperty("SaleType")
    private String saleType; // USER_INITIATED_BANK, USER_INITIATED_MPESA, BANK, MPESA

    public PaymentRequest() {}

    public String getOriginatorConversationID() {
        return originatorConversationID;
    }
    public void setOriginatorConversationID(String originatorConversationID) {
        this.originatorConversationID = originatorConversationID;
    }

    public String getInitiatorName() { return initiatorName; }
    public void setInitiatorName(String initiatorName) { this.initiatorName = initiatorName; }

    public String getSecurityCredential() { return securityCredential; }
    public void setSecurityCredential(String securityCredential) { this.securityCredential = securityCredential; }

    public String getCommandID() { return commandID; }
    public void setCommandID(String commandID) { this.commandID = commandID; }

    public Double getAmount() { return amount; }
    public void setAmount(Double amount) { this.amount = amount; }

    public String getPartyA() { return partyA; }
    public void setPartyA(String partyA) { this.partyA = partyA; }

    public String getPartyB() { return partyB; }
    public void setPartyB(String partyB) { this.partyB = partyB; }

    public String getRemarks() { return remarks; }
    public void setRemarks(String remarks) { this.remarks = remarks; }

    public String getQueueTimeOutURL() { return queueTimeOutURL; }
    public void setQueueTimeOutURL(String queueTimeOutURL) { this.queueTimeOutURL = queueTimeOutURL; }

    public String getResultURL() { return resultURL; }
    public void setResultURL(String resultURL) { this.resultURL = resultURL; }

    public String getOccasion() { return occasion; }
    public void setOccasion(String occasion) { this.occasion = occasion; }

    public String getSaleType() { return saleType; }
    public void setSaleType(String saleType) { this.saleType = saleType; }

    @Override
    public String toString() {
        return "PaymentRequest{" +
                "originatorConversationID='" + originatorConversationID + '\'' +
                ", initiatorName='" + initiatorName + '\'' +
                ", commandID='" + commandID + '\'' +
                ", amount=" + amount +
                ", partyA='" + partyA + '\'' +
                ", partyB='" + partyB + '\'' +
                ", remarks='" + remarks + '\'' +
                ", queueTimeOutURL='" + queueTimeOutURL + '\'' +
                ", resultURL='" + resultURL + '\'' +
                ", occasion='" + occasion + '\'' +
                ", saleType='" + saleType + '\'' +
                '}';
    }
}
